defaults:
  - model: nanogpt
  - writer: wandb
  - metrics: lm_training
  - datasets: openwebtext_10k
  - dataloader: train_val_dataloaders
  - optimizer: adamw
  - _self_

datasets:
  train:
    max_seq_len: ${model.block_size}
  val:
    max_seq_len: ${model.block_size}

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-3
  pct_start: 0.02
  div_factor: 10.0
  final_div_factor: 10.0
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.NLLLoss

batch_size: 32
num_workers: 4
pad_id: 0
vocab_size: 50304

trainer:
  log_step: 50
  n_epochs: 10
  epoch_len: 500
  device_tensors: ["input_ids", "targets"]
  resume_from: null
  device: auto
  override: true
  monitor: "min val_perplexity"
  save_period: 100000
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  parallel: false
  seed: 1
  dtype: bfloat16
  accumulation_steps: 1
  max_grad_norm: null
  skip_oom: true
  compute_matrix_metrics: true
  compute_topsubspace_metrics: false
  topsubspace_k: 5

writer:
  run_name: "nanogpt"
